apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fashion-classifier
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fashion-classifier
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fashion-classifier
    spec:
      containers:
      - name: fashion-classifier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }} 