apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fashion-classifier-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-fashion-classifier
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8501
  - name: http-metrics
    protocol: TCP
    port: 8080
    targetPort: 8080 